### ISSUE TITLE
Edge classification with same networks?

### ISSUE THREAD

**Issue by monk1337** [ShinKyuY/Graph-Neural-Net#1]
Hi, I just found your repository and and it's really helpful to understand graph networks and it's variants. 
I just gone through your notebook and it was really informative and maintained.
In your experiments you have only predicted node and presented node classification problem.
I have few doubts, can we use same networks for edge classification or do we have other powerful networks for edge classification instead of node classification?
If you can post a notebook with edge classification that would be very helpful though. 

Thank you,
And  keep posting and learning. :)

**Comment by ShinKyuY** [comment]
Thank you for reviewing my repository. I don't know much about edge classification. However, as far as I know, there is an edge-generating network. The Variational Graph Auto-Encodes is that network.

**Comment by ShinKyuY** [comment]
> Hi, I just found your repository and and it's really helpful to understand graph networks and it's variants.
> I just gone through your notebook and it was really informative and maintained.
> In your experiments you have only predicted node and presented node classification problem.
> I have few doubts, can we use same networks for edge classification or do we have other powerful networks for edge classification instead of node classification?
> If you can post a notebook with edge classification that would be very helpful though.
> 
> Thank you,
> And keep posting and learning. :)

Thank you for reviewing my repository. I don't know much about edge classification. However, as far as I know, there is an edge-generating network. The Variational Graph Auto-Encodes is that network.

**Comment by jjyock** [comment]
can you share the notebook data with me ? thank you
